'use client';
import { useState } from 'react';
import { useCart } from '@/context/CartContext';
type Invoice={id:string;date:string;customer:string;lines:{title:string;color:string;quantity:number;price:number}[];subtotal:number;delivery:number;assembly:number;total:number};
const money=(n:number)=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format(n);
export default function AlashiCheckout(){
  const {items,total,clearCart,updateQuantity,removeItem}=useCart();const [customer,setCustomer]=useState({name:'',email:'',phone:'',address:'',city:'',postcode:''});const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [delivery,setDelivery]=useState<number|null>(null);const [invoice,setInvoice]=useState<Invoice>();
  async function check(){setError('');try{const r=await fetch(`/api/alashi/checkout/?postcode=${encodeURIComponent(customer.postcode)}`);const d=await r.json();if(!r.ok)throw new Error(d.error);setDelivery(d.delivery);if(d.needsOwner)setError('Please contact Samiullah to confirm delivery for this postcode.');}catch(e){setError(e instanceof Error?e.message:'Could not check delivery.');}}
  if(invoice)return <section className="max-w-3xl mx-auto my-12 p-8 bg-white rounded-2xl"><h1 className="text-3xl mb-4">Corner Sofa UK · Challan</h1><p>{invoice.id} · {new Date(invoice.date).toLocaleDateString('en-GB')}</p><p className="my-3">{invoice.customer} · Cash on Delivery</p><p>Order request received, awaiting confirmation from Samiullah.</p><div className="my-6">{invoice.lines.map((p,i)=><p key={i} className="py-3 border-b">{p.title} · {p.color} · {money(p.price)} × {p.quantity} = {money(p.price*p.quantity)}</p>)}</div><p>Subtotal (VAT included): {money(invoice.subtotal)}</p><p>Delivery: {money(invoice.delivery)}</p><p>Assembly: {money(invoice.assembly)}</p><strong className="block text-2xl my-5">Total due on delivery: {money(invoice.total)}</strong><button className="bg-[#263b30] text-white rounded-xl px-6 py-3 print:hidden" onClick={()=>window.print()}>Print / save challan as PDF</button><p className="mt-5">Delivery: 3–4 working days after order confirmation.</p></section>;
  if(!items.length)return <section className="max-w-xl mx-auto py-24 text-center"><h1 className="text-3xl mb-5">Your basket is empty</h1><a href="/products/" className="underline">Browse sofas</a></section>;
  return <section className="max-w-4xl mx-auto px-5 py-12"><h1 className="text-3xl mb-3">Cash on Delivery checkout</h1><p className="mb-8">Confirm your sofa, colour and quantity. Prices include VAT. Assembly is £20 per order.</p><div className="bg-white p-6 rounded-2xl mb-6">{items.map(p=><div key={p.productId+p.variantId} className="flex gap-4 items-center border-b py-4"><img src={p.image} alt={p.title} className="w-20 h-20 rounded-xl object-cover"/><div className="flex-1"><strong>{p.title}</strong><p>{p.color} · {money(p.price)} each</p><label>Quantity <input aria-label={`Quantity for ${p.title}`} type="number" min="1" max="10" value={p.quantity} className="border rounded w-16 p-1" onChange={e=>updateQuantity(p.productId,p.variantId,Number(e.target.value))}/></label><button className="ml-4 underline text-xs" onClick={()=>removeItem(p.productId,p.variantId)}>Remove</button></div><b>{money(p.price*p.quantity)}</b></div>)}<p className="mt-5">Subtotal: {money(total)}</p><p>Assembly: £20.00</p><p>Delivery: {delivery===null?'Enter postcode to check':money(delivery)}</p><strong>Total: {delivery===null?'Awaiting delivery quote':money(total+20+delivery)}</strong></div><form className="bg-white p-6 rounded-2xl" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/alashi/checkout/',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({items,customer})});const d=await r.json();if(!r.ok)throw new Error(d.error);setInvoice(d.invoice);clearCart();}catch(e){setError(e instanceof Error?e.message:'Could not submit.');}finally{setBusy(false);}}}><div className="grid md:grid-cols-2 gap-4">{Object.keys(customer).map(k=><label key={k} className="capitalize">{k}<input required type={k==='email'?'email':k==='phone'?'tel':'text'} maxLength={300} value={customer[k as keyof typeof customer]} onChange={e=>{setCustomer({...customer,[k]:e.target.value});if(k==='postcode')setDelivery(null);}} className="block w-full border border-gray-300 p-3 rounded-xl mt-2"/></label>)}</div><button type="button" className="underline my-5" onClick={check}>Check delivery postcode</button><p className="mb-5">Payment: Cash on Delivery only. Your order request and agreed price are checked on the server before a challan is created.</p><button disabled={busy||delivery===null} className="bg-[#263b30] text-white rounded-xl px-6 py-3 disabled:opacity-40">{busy?'Submitting…':'Place order request & create challan'}</button>{error&&<p role="alert" className="text-red-700 mt-4">{error}</p>}</form></section>;
}
